---
- hosts: galaxy_servers
  sudo: yes
  sudo_user: galaxy

  tasks: 
  - name: Check if galaxy pid file exists.
    command: /usr/bin/test -e {{ GALAXY_HOME }}/web0.pid
    ignore_errors: True
    register: galaxy_running
 
  - name: scheduled maintenance
    sudo: yes
    sudo_user: galaxy
    file: src={{ GALAXY_HOME }}/../www/html/error-documents/503_scheduled_maintenance.html
          dest={{ GALAXY_HOME }}/../www/html/error-documents/503.html
          state=link 
    when: galaxy_running.rc == 0
  
  - name: stop galaxy
    sudo: yes
    sudo_user: galaxy
    environment:
      GALAXY_RUN_ALL: 1
    shell: "source {{ GALAXY_HOME }}/../galaxy-env/bin/activate && /bin/sh {{ GALAXY_HOME }}/run.sh --stop-daemon"
    when: galaxy_running.rc == 0
  
  - name: Check if reports pid file exists.
    command: /usr/bin/test -e {{ GALAXY_HOME }}/reports_webapp.pid
    ignore_errors: True
    register: reports_running
  
  - name: stop reports
    sudo: yes
    sudo_user: galaxy
    environment:
      GALAXY_RUN_ALL: 1
    shell: "source {{ GALAXY_HOME }}/../galaxy-env/bin/activate && /bin/sh {{ GALAXY_HOME }}/run_reports.sh --stop-daemon"
    when: reports_running.rc == 0
