---
- hosts: galaxy_servers
  become: yes
  become_user: galaxy
  become_method: sudo
  vars_files:
    -  "{{ env }}/secrets/passwords.yaml"
  roles:
    - role: galaxy
    - role: galaxy_legacy_tools
      tags: [ never, legacy_tools ]
