---
- hosts: galaxy_servers
  sudo: yes
  sudo_user: galaxy

  tasks:

  - name: start galaxy
    sudo: yes
    sudo_user: galaxy
    environment:
      GALAXY_RUN_ALL: 1
      PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    shell: "source {{ GALAXY_HOME }}/../galaxy-env/bin/activate && /bin/sh {{ GALAXY_HOME }}/run.sh --daemon"

  - name: normal operation
    sudo: yes
    sudo_user: galaxy
    file: src={{ GALAXY_HOME }}/../www/html/error-documents/503_outage.html
          dest={{ GALAXY_HOME }}/../www/html/error-documents/503.html
          state=link

  - name: start reports
    sudo: yes
    sudo_user: galaxy
    environment:
      GALAXY_RUN_ALL: 1
      PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    shell: "source {{ GALAXY_HOME }}/../galaxy-env/bin/activate && /bin/sh {{ GALAXY_HOME }}/run_reports.sh --daemon"
