---
- name: tool-dependencies directory
  file: path="{{ GALAXY_HOME }}/tool-dependencies/" state=directory

- name: tool-dependencies directory copy
  copy:
      src: "tool-dependencies/"
      dest: "{{ GALAXY_HOME }}/tool-dependencies/"
      follow: no
      local_follow: no

      # - name: tool-dependencies sub-directories
      #   file: 
      #     path: "{{ GALAXY_HOME }}/tool-dependencies/{{ item }}"
      #     state: directory
      #   with_items:
      #     - "EXPORT_DIR_PREFIX/0.0.1"

- name: tool-dependencies templates
  template:
    src: "tool-dependencies/{{ item }}.j2"
    dest: "{{ GALAXY_HOME }}/tool-dependencies/{{ item }}"
    mode: 0640
    backup: "yes"
  with_items:
    - "EXPORT_DIR_PREFIX/0.0.1/env.sh"

- name: tool dependencies default links
  file:
      src: "{{ GALAXY_HOME }}/tool-dependencies/{{ item.tool }}/{{ item.version }}"
      dest: "{{ GALAXY_HOME }}/tool-dependencies/{{ item.tool }}/default"
      state: link
  with_items:
      - { tool: 'EXPORT_DIR_PREFIX', version: '0.0.1' }

- name: create galaxy_export directory
  file:
      path: "{{ export_dir }}"
      state: directory
      mode: 0771
