- name: create database backup cron script
  template:
    src: "backup_pg_database.sh.j2"
    dest: "{{ GALAXY_HOME }}/cron/backup_pg_database.sh"
    mode: 0755

- name: create dataset cleanup cron script
  template:
    src: "dataset_cleanup.sh.j2"
    dest: "{{ GALAXY_HOME }}/cron/dataset_cleanup.sh"
    mode: 0755

- name: create user disk usage cron script
  template:
      src: "set_user_disk_usage.sh.j2"
      dest: "{{ GALAXY_HOME }}/cron/set_user_disk_usage.sh"
      mode: 0755

- name: create updateucsc cron script
  template:
      src: "updateucsc.sh.j2"
      dest: "{{ GALAXY_HOME }}/cron/updateucsc.sh"
      mode: 0755

- name: create scripts directory
  file: dest={{ GALAXY_HOME }}/scripts/ state=directory

- name: create scripts logs directory
  file: dest={{ GALAXY_HOME }}/scripts/logs state=directory

- name: create dataset_cleanup scripts directory
  file: dest={{ GALAXY_HOME }}/scripts/cleanup_datasets state=directory

- name: copy dataset_cleanup scripts
  copy: src={{ item }} dest={{ GALAXY_HOME }}/scripts/cleanup_datasets owner=galaxy mode=755
  with_fileglob:
        - scripts/cleanup_datasets/*


- name: set MAILTO in crontab
  cron:
    name: "MAILTO"
    minute: "MAILTO={{ crontab_mailto }}"
    hour: ""
    day: ""
    month: ""
    weekday: ""
    job: ""

- name: crontab entry to backup Galaxy database
  cron:
    name: "backup galaxy database"
    minute: "0"
    hour: "1"
    day: "*"
    month: "*"
    weekday: "*"
    job: "{{ GALAXY_HOME }}cron/backup_pg_database.sh"

- name: crontab entry to cleanup datasets
  cron:
    name: "cleanup galaxy datasets"
    minute: "0"
    hour: "2"
    day: "*"
    month: "*"
    weekday: "*"
    job: "export PATH=/usr/local/bin:$PATH; {{ GALAXY_HOME }}/cron/dataset_cleanup.sh >/dev/null"

- name: crontab entry to set Galaxy user disk usage
  cron:
    name: "set galaxy user disk usage"
    minute: "0"
    hour: "4"
    day: "*"
    month: "*"
    weekday: "*"
    job: "export PATH=/usr/local/bin:$PATH; {{ GALAXY_HOME }}/cron/set_user_disk_usage.sh"

- name: crontab entry to cleanup Galaxy temp files
  cron:
    name: "cleanup galaxy tempfiles"
    minute: "0"
    hour: "5"
    day: "*"
    month: "*"
    weekday: "*"
    job: "/usr/sbin/tmpwatch -u 168 {{ GALAXY_HOME }}/database/tmp"

- name: crontab entry to update ucsc genomes
  cron:
    name: "update ucsc genomes"
    minute: "0"
    hour: "6"
    day: "*"
    month: "*"
    weekday: "*"
    job: "{{ GALAXY_HOME }}cron/updateucsc.sh"
