---
# Hide specific tools from tools menu
#####################################

- name: test shed_tool_conf.xml exists
  stat:
    path: "{{ config_directory }}/shed_tool_conf.xml"
  register: "shed_tool_conf"

- name: Add hidden tag to shed_tool_conf.xml file
  lineinfile:
    dest: "{{ config_directory }}/shed_tool_conf.xml"
    regexp: '(^\s*<tool .* guid="{{ item }}")>'
    backrefs: yes
    line: '\1 hidden="True">'
    state: present
  when: shed_tool_conf.stat.exists == True
  with_items:
      - toolshed\.g2\.bx\.psu\.edu/repos/pcingola/snpeff/snpEff/1\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/pcingola/snpeff/snpEff_download/1\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/pcingola/snpeff/snpSift_int/1\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/pcingola/snpeff/snpSift_filter/1\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/pcingola/snpeff/snpSift_annotate/1\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/pcingola/snpeff/snpSift_caseControl/1\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/iuc/snpeff/snpEff_download/4\.0\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/aaronquinlan/bedtools/bedtools_intersectbed_bam/0\.1\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/aaronquinlan/bedtools/bedtools_coveragebed_counts/0\.1\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/aaronquinlan/bedtools/bedtools_genomecoveragebed_histogram/0\.1\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/aaronquinlan/bedtools/bedtools_genomecoveragebed_bedgraph/0\.1\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/aaronquinlan/bedtools/bedtools_bamtobed/0\.1\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/aaronquinlan/bedtools/bedtools_mergebedgraph/0\.1\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/aaronquinlan/bedtools/bedtools_multiintersectbed/0\.1\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/devteam/picard/PicardASMetrics/1\.56\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/devteam/picard/picard_ARRG/1\.56\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/devteam/picard/rgEstLibComp/1\.56\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/devteam/picard/PicardHsMetrics/1\.56\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/devteam/picard/picard_SamToFastq/1\.56\.1
      - toolshed\.g2\.bx\.psu\.edu/repos/devteam/picard/PicardGCBiasMetrics/1\.56\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/devteam/picard/PicardInsertSize/1\.56\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/devteam/picard/rgPicFixMate/1\.56\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/devteam/picard/picard_ReplaceSamHeader/1\.56\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/devteam/picard/rgPicardMarkDups/1\.56\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/devteam/picard/picard_BamIndexStats/1\.56\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/iuc/bedtools/bedtools_genomecoveragebed_bedgraph/2\.19\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/iuc/bedtools/bedtools_mergebedgraph/2\.19\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/iuc/bedtools/bedtools_bamtofastq/2\.19\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/iuc/bedtools/bedtools_genomecoveragebed_histogram/2\.19\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/bgruening/deeptools/deeptools_heatmapper/1\.5\.9\.1\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/bgruening/deeptools/deeptools_bigwigCompare/1\.5\.9\.1\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/bgruening/deeptools/deeptools_bamCoverage/1\.5\.9\.1\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/bgruening/deeptools/deeptools_correctGCBias/1\.5\.9\.1\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/bgruening/deeptools/deeptools_bamCompare/1\.5\.9\.1\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/bgruening/deeptools/deeptools_bamFingerprint/1\.5\.9\.1\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/bgruening/deeptools/deeptools_profiler/1\.5\.9\.1\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/bgruening/deeptools/deeptools_computeGCBias/1\.5\.9\.1\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/bgruening/deeptools/deeptools_computeMatrix/1\.5\.9\.1\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/bgruening/deeptools/deeptools_bamCorrelate/1\.5\.9\.1\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/bgruening/deeptools/deeptools_bamPEFragmentSize/1\.5\.9\.1\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/bgruening/text_processing/tp_tail_tool/1\.0\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/bgruening/text_processing/tp_head_tool/1\.0\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/bgruening/text_processing/tp_cat/0\.1\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/bgruening/text_processing/tp_cut_tool/1\.0\.0
      - toolshed\.g2\.bx\.psu\.edu/repos/iuc/trinity/samples_qccheck/2\.1\.1
      - toolshed\.g2\.bx\.psu\.edu/repos/iuc/trinity/abundance_estimates_to_matrix/2\.1\.1\.1
      - toolshed\.g2\.bx\.psu\.edu/repos/iuc/trinity/align_and_estimate_abundance/2\.1\.1\.1
      - toolshed\.g2\.bx\.psu\.edu/repos/iuc/trinity/run_DE_analysis/2\.1\.1\.1
      - toolshed\.g2\.bx\.psu\.edu/repos/devteam/variant_select/gatk_variant_select/0\.0\.3
      - toolshed\.g2\.bx\.psu\.edu/repos/devteam/print_reads/gatk_print_reads/0\.0\.2
      - toolshed\.g2\.bx\.psu\.edu/repos/devteam/unified_genotyper/gatk_unified_genotyper/0\.0\.6
      
- name: test migrated_tools_conf.xml exists
  stat:
    path: "{{ config_directory }}/migrated_tools_conf.xml"
  register: "migrated_tools_conf"

- name: Add hidden tag to migrated_tools_conf.xml file
  lineinfile:
    dest: "{{ config_directory }}/migrated_tools_conf.xml"
    regexp: '(^\s*<tool .* guid="{{ item }}")>'
    backrefs: yes
    line: '\1 hidden="True">'
    state: present
  when: migrated_tools_conf.stat.exists == True
  with_items:
      - toolshed\.g2\.bx\.psu\.edu/repos/devteam/print_reads/gatk_print_reads/0\.0\.1
      - toolshed\.g2\.bx\.psu\.edu/repos/devteam/variant_select/gatk_variant_select/0\.0\.2
      - toolshed\.g2\.bx\.psu\.edu/repos/devteam/variant_annotator/gatk_variant_annotator/0\.0\.5
      - toolshed\.g2\.bx\.psu\.edu/repos/devteam/variant_recalibrator/gatk_variant_recalibrator/0\.0\.4
      - toolshed\.g2\.bx\.psu\.edu/repos/devteam/variant_filtration/gatk_variant_filtration/0\.0\.5
      - toolshed\.g2\.bx\.psu\.edu/repos/devteam/variant_eval/gatk_variant_eval/0\.0\.8
      - toolshed\.g2\.bx\.psu\.edu/repos/devteam/variant_combine/gatk_variant_combine/0\.0\.4
      - toolshed\.g2\.bx\.psu\.edu/repos/devteam/variant_apply_recalibration/gatk_variant_apply_recalibration/0\.0\.4
      - toolshed\.g2\.bx\.psu\.edu/repos/devteam/table_recalibration/gatk_table_recalibration/0\.0\.5
      - toolshed\.g2\.bx\.psu\.edu/repos/devteam/realigner_target_creator/gatk_realigner_target_creator/0\.0\.4
      - toolshed\.g2\.bx\.psu\.edu/repos/devteam/print_reads/gatk_print_reads/0\.0\.1
      - toolshed\.g2\.bx\.psu\.edu/repos/devteam/indel_realigner/gatk_indel_realigner/0\.0\.6
      - toolshed\.g2\.bx\.psu\.edu/repos/devteam/depth_of_coverage/gatk_depth_of_coverage/0\.0\.2
      - toolshed\.g2\.bx\.psu\.edu/repos/devteam/count_covariates/gatk_count_covariates/0\.0\.5
      - toolshed\.g2\.bx\.psu\.edu/repos/devteam/analyze_covariates/gatk_analyze_covariates/0\.0\.5
      - toolshed\.g2\.bx\.psu\.edu/repos/devteam/unified_genotyper/gatk_unified_genotyper/0\.0\.6