---
- name: test connection
  ping:

- name: create error-documents folder
  file: path={{ GALAXY_HOME }}/../www/html/error-documents/ state=directory mode=755

- name: error-documents
  copy: src="error-documents/" dest={{ GALAXY_HOME }}/../www/html/error-documents/ mode=0644

- name: set galaxy user git config
  copy: src="git_config/gitconfig" dest="{{ ansible_env.HOME }}/.gitconfig"
  tags:
    - userconfig

- stat: path="{{ GALAXY_HOME }}/.git"
  register: git

- include: stop_galaxy.yml

- name: checkout upstream branch
  command: "{{ git_executable | default('git') }} checkout {{ galaxy_changeset_id }} chdir={{ GALAXY_HOME }}"
  args:
    chdir: "{{ GALAXY_HOME }}"
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  when: git.stat.isdir is defined and git.stat.isdir == true

- include: backup_loc_files.yaml

- name: Get current Galaxy commit id (git)
  command: "{{ git_executable | default('git') }} rev-parse HEAD chdir={{ GALAXY_HOME }}"
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: current_changeset_id
  changed_when: False
  when: git.stat.isdir is defined and git.stat.isdir == true

- name: Report current Galaxy changeset
  debug:
    msg: "Current changeset of {{ GALAXY_HOME }} {{ current_changeset_id.stdout }} does not match playbook version {{ galaxy_changeset_id }}"
  changed_when: True
  when: current_changeset_id.stdout != galaxy_changeset_id
  when: git.stat.isdir is defined and git.stat.isdir == true

- name: Get current tool migration stages
  shell: ls -1 *tools.sh | sort chdir={{ GALAXY_HOME }}/scripts/migrate_tools/
  register: current_tool_migration_stages
  changed_when: False
  when: git.stat.isdir is defined and git.stat.isdir == true

- name: Update galaxy to correct changeset
  git:
    dest: "{{ GALAXY_HOME }}"
    force: "yes"
    repo: "https://github.com/galaxyproject/galaxy.git"
    version: "{{ galaxy_changeset_id }}"
    executable: "{{ git_executable | default(omit) }}"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  #notify:
  #  - restart galaxy

- name: Get updated tool migration stage
  shell: ls -1 *tools.sh | sort chdir={{ GALAXY_HOME }}/scripts/migrate_tools/
  register: updated_tool_migration_stages
  changed_when: False

- include: patches.yml

- name: add legacy tools (not from toolshed)
  copy: src="galaxy_legacy_tools/tools/" dest="{{ GALAXY_HOME }}/tools/" backup=yes

- name: add legacy tool test-data
  copy: src="galaxy_legacy_tools/test-data/" dest="{{ GALAXY_HOME }}/test-data/" backup=yes

- name: add legacy jars
  copy: src="galaxy_legacy_tools/tool-data/" dest="{{ GALAXY_HOME }}/tool-data/" backup=yes

- name: universe_wsgi.ini
  template: src=universe_wsgi.ini.j2 dest={{ GALAXY_HOME }}/universe_wsgi.ini backup=yes

- name: job_conf.xml
  template: src=job_conf.xml.j2 dest={{ GALAXY_HOME }}/job_conf.xml backup=yes

- name: tool_sheds_conf.xml
  template: src=tool_sheds_conf.xml.j2 dest={{ GALAXY_HOME }}/tool_sheds_conf.xml backup=yes

- name: reports_wsgi.ini
  template: src=reports_wsgi.ini.j2 dest={{ GALAXY_HOME }}/reports_wsgi.ini backup=yes

- name: tool_conf.xml
  template: src=tool_conf.xml.j2 dest={{ GALAXY_HOME }}/tool_conf.xml backup=yes

- name: tool_data_table_conf.xml
  copy: src="config/tool_data_table_conf.xml" dest="{{ GALAXY_HOME }}/tool_data_table_conf.xml" backup=yes

- include: hide_tools.yml

- name: tool-data
  copy:
    src: "tool-data/"
    dest: "{{ GALAXY_HOME }}/tool-data/"
    backup: yes
  register: tooldata

- name: update builds
  command: "{{ galaxy_venv_dir }}/bin/python cron/add_manual_builds.py tool-data/shared/ucsc/manual_builds.txt tool-data/shared/ucsc/builds.txt tool-data/shared/ucsc/chrom/ chdir={{ GALAXY_HOME }}"
  when: tooldata.changed

- name: welcome.html
  template: src=welcome.html.j2 dest={{ GALAXY_HOME }}/static/welcome.html backup=yes

- include: tool-dependencies.yaml

- include: crontab.yaml

- include: custom_scripts.yaml

- include: taxonomy_tool_data.yaml

- name: Get current Galaxy DB version
  command: "{{ galaxy_venv_dir }}/bin/python {{ GALAXY_HOME }}/scripts/manage_db.py db_version chdir={{ GALAXY_HOME }}"
  register: current_db_version
  changed_when: False

- name: Get maximum Galaxy DB version
  command: "{{ galaxy_venv_dir }}/bin/python {{ GALAXY_HOME }}/scripts/manage_db.py version chdir={{ GALAXY_HOME }}"
  register: max_db_version
  changed_when: False

- include: backup_database.yaml
  when: current_db_version.stdout != max_db_version.stdout

- name: Upgrade Galaxy DB
  command: "{{ galaxy_venv_dir }}/bin/python {{ GALAXY_HOME }}/scripts/manage_db.py upgrade chdir={{ GALAXY_HOME }}"
  when: current_db_version.stdout != max_db_version.stdout

- name: Report current tool migration stage
  debug:
    msg: "There are {{ updated_tool_migration_stages.stdout_lines|length - current_tool_migration_stages.stdout_lines|length }} new tool migration stages for {{ GALAXY_HOME }}"
  changed_when: True
  when: current_tool_migration_stages.stdout_lines|length != updated_tool_migration_stages.stdout_lines|length

- name: Run tool migrations
  shell: ". {{ galaxy_venv_dir}}/bin/activate && sh ./scripts/migrate_tools/{{ item }} install_dependencies chdir={{ GALAXY_HOME }}"
  changed_when: True
  when: updated_tool_migration_stages.stdout_lines|length - current_tool_migration_stages.stdout_lines|length > 0
  with_items:
    updated_tool_migration_stages.stdout_lines[-(updated_tool_migration_stages.stdout_lines|length - current_tool_migration_stages.stdout_lines|length)]

- name: Create tool_conf.xml patch
  shell: "diff -u tool_conf.xml-pre-stage-{{ item[:4] }} tool_conf.xml > tool_conf.xml-{{ item[:4] }}.diff chdir={{ GALAXY_HOME }} creates={{ GALAXY_HOME }}/tool_conf.xml-{{ item[:4] }}.diff"
  changed_when: True
  when: updated_tool_migration_stages.stdout_lines|length - current_tool_migration_stages.stdout_lines|length > 0
  with_items:
    updated_tool_migration_stages.stdout_lines[-1]
  register: diff_result
  failed_when: diff_result.rc > 1

- name: Fetch tool_conf.xml diff
  fetch: src={{ GALAXY_HOME }}/tool_conf.xml-{{ item[:4] }}.diff dest=tool_conf_diffs/{{ ansible_hostname }}/tool_conf.xml-{{ item[:4] }}.diff flat=yes
  when: updated_tool_migration_stages.stdout_lines|length - current_tool_migration_stages.stdout_lines|length > 0
  with_items:
    updated_tool_migration_stages.stdout_lines[-1]

- include: start_galaxy.yml
