---
- name: test connection
  ping:

- name: set galaxy user hg config
  copy: src="hg_config/.hgrc" dest="~"

- name: Check if pid file exists.
  command: /usr/bin/test -e {{ GALAXY_HOME }}/web0.pid
  ignore_errors: True
  register: galaxy_running

- include: stop.yaml
  when: galaxy_running.rc == 0

- name: checkout galaxy
  hg: repo=https://bitbucket.org/galaxy/galaxy-dist#stable
      dest={{ GALAXY_HOME }}
      revision=d3b1f484c4b6
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}

- name: checkout galaxy patches
  hg: repo=https://bitbucket.org/princeton_genomics/galaxy_patches
      dest={{ GALAXY_HOME }}/.hg/patches
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}

- name: apply galaxy patches
  command: hg qpush -a
  args:
    chdir: "{{ GALAXY_HOME }}"
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}

- name: add legacy tools (not from toolshed)
  copy: src="galaxy_legacy_tools/" dest="{{ GALAXY_HOME }}/tools/"

- name: universe_wsgi.ini
  template: src=universe_wsgi.ini.j2 dest={{ GALAXY_HOME }}/universe_wsgi.ini

- name: job_conf.xml
  template: src=job_conf.xml.j2 dest={{ GALAXY_HOME }}/job_conf.xml

- name: reports_wsgi.ini
  template: src=reports_wsgi.ini.j2 dest={{ GALAXY_HOME }}/reports_wsgi.ini

- name: tool_conf.xml
  template: src=tool_conf.xml.j2 dest={{ GALAXY_HOME }}/tool_conf.xml

- name: welcome.html
  template: src=welcome.html.j2 dest={{ GALAXY_HOME }}/static/welcome.html

- include: tool-dependencies.yaml

- name: error-documents
  copy: src="error-documents" dest={{ GALAXY_HOME }}/../www/html/

- include: crontab.yaml

- name: custom scripts
  copy: src="scripts/" dest="{{ GALAXY_HOME }}/scripts/"

- include: start.yaml

