---
# Apply various patches to Galaxy
#################################

- name: create pathces folder
  file: path={{ GALAXY_HOME }}/patches state=directory
  tags: patch

- name: Copy patches to remote host (required due to Ansible bug)
  copy:
    src: "patches/"
    dest: "{{ GALAXY_HOME }}/patches/"
  tags: patch

- name: Apply patches
  patch:
    src: "{{ GALAXY_HOME }}/patches/{{ item | basename }}"
    basedir: "{{ GALAXY_HOME }}"
    strip: 1
    remote_src: True
  with_fileglob:
    - "patches/*.patch"
  tags: patch
