- name: copy start script
  copy: src=galaxy_start.sh dest={{ GALAXY_HOME }}/ owner=galaxy mode=755

- name: start galaxy
  sudo: yes
  sudo_user: galaxy
  shell: "/bin/sh {{ GALAXY_HOME }}/galaxy_start.sh"
  tags:
    - restart
    - start

- name: Wait for Galaxy to start
  wait_for: port=8080 delay=5 state=started timeout=150
  tags:
    - restart
    - start

- name: Set 503 message to unplanned outage
  file: src={{ GALAXY_HOME }}/../www/html/error-documents/503_outage.html
        dest={{ GALAXY_HOME }}/../www/html/error-documents/503.html
        state=link
  tags:
    - restart
    - start
