---
- name: start galaxy
  sudo: yes
  sudo_user: galaxy
  environment:
    GALAXY_RUN_ALL: 1
  shell: "source {{ GALAXY_HOME }}/../galaxy-env/bin/activate && /bin/sh {{ GALAXY_HOME }}/run.sh --daemon"
