- name: Set 503 message to known outage
  file: src={{ GALAXY_HOME }}/../www/html/error-documents/503_known_outage.html
        dest={{ GALAXY_HOME }}/../www/html/error-documents/503.html
        state=link

- name: Check if galaxy pid file exists.
  command: /usr/bin/test -e {{ GALAXY_HOME }}/web0.pid
  ignore_errors: True
  register: galaxy_running

- name: copy stop script
  copy: src=galaxy_stop.sh dest={{ GALAXY_HOME }}/ owner=galaxy mode=755

- name: stop galaxy
  sudo: yes
  sudo_user: galaxy
  environment:
    GALAXY_RUN_ALL: 1
  shell: "/bin/sh {{ GALAXY_HOME }}/galaxy_stop.sh"
  when: galaxy_running.rc == 0

- name: Wait for Galaxy to stop
  wait_for: port=8080 delay=5 state=stopped timeout=150
