- name: Check if galaxy pid file exists.
  command: /usr/bin/test -e {{ GALAXY_HOME }}/web0.pid
  ignore_errors: True
  register: galaxy_running
  tags:
    - restart
    - stop

- name: stop galaxy
  sudo: yes
  sudo_user: galaxy
  environment:
    GALAXY_RUN_ALL: 1
  shell: "/bin/sh {{ GALAXY_HOME }}/galaxy_stop.sh"
  when: galaxy_running.rc == 0
  tags:
    - restart
    - stop

- name: Wait for Galaxy to stop
  wait_for: port=8080 delay=5 state=stopped timeout=150
  tags:
    - restart
    - stop

# - name: remove integrated_tool_panel.xml
#   file: path="{{ GALAXY_HOME }}/integrated_tool_panel.xml" state="absent"
#   when: galaxy_running.rc == 0
#   tags:
#     - restart
#     - stop
