---

- name: make sure tool-dependencies folder exists
  file: path="{{ GALAXY_HOME }}/tool-dependencies/" state=directory

- name: tool-dependencies directory copy
  copy: src="tool-dependencies/" dest="{{ GALAXY_HOME }}/tool-dependencies/"

- name: bedtools_links
  file: src="{{ GALAXY_HOME }}/tool-dependencies/bedtools"
        dest={{ item }}
        state=link force=yes
  with_items:
      - "{{ GALAXY_HOME }}/tool-dependencies/bamToBed"
      - "{{ GALAXY_HOME }}/tool-dependencies/coverageBed"
      - "{{ GALAXY_HOME }}/tool-dependencies/genomeCoverageBed"
      - "{{ GALAXY_HOME }}/tool-dependencies/intersectBed"
      - "{{ GALAXY_HOME }}/tool-dependencies/multiIntersectBed"
      - "{{ GALAXY_HOME }}/tool-dependencies/unionBedGraphs"

- name: tool dependencies default links
  file: src={{ GALAXY_HOME }}/tool-dependencies/{{ item.tool }}/{{ item.version }}
        dest={{ GALAXY_HOME }}/tool-dependencies/{{ item.tool }}/default
        state=link
  with_items:
      - { tool: 'bedtools', version: '2.16.2' }
      - { tool: 'bwa', version: '0.5.10' }
      - { tool: 'SICER', version: '1.1' }
      - { tool: 'bowtie2', version: '2.1.0' }
      - { tool: 'cufflinks', version: '2.1.1' }
      - { tool: 'freebayes', version: '0.9.4' }
      - { tool: 'htseq', version: '0.5.3p9' }
      - { tool: 'macs', version: '1.3.7.1' }
      - { tool: 'macs14', version: '1.4.2' }
      - { tool: 'numpy', version: '1.6.2' }
      - { tool: 'sambamba', version: '0.3.3' }
      - { tool: 'samtools', version: '0.1.18' }
      - { tool: 'tophat', version: '1.4.0' }
      - { tool: 'tophat2', version: '2.0.8b' }
