---
- name: tool-dependencies
  copy: src="tool-dependencies" dest={{ GALAXY_HOME }}
        recurse=yes state=directory backup=yes

- name: bamToBed
  file: src="{{ GALAXY_HOME }}/tool-dependencies/bedtools"
        dest="{{ GALAXY_HOME }}/tool-dependencies/bamToBed"
        state=link

- name: coverageBed
  file: src="{{ GALAXY_HOME }}/tool-dependencies/bedtools"
        dest="{{ GALAXY_HOME }}/tool-dependencies/coverageBed"
        state=link

- name: genomeCoverageBed
  file: src="{{ GALAXY_HOME }}/tool-dependencies/bedtools"
        dest="{{ GALAXY_HOME }}/tool-dependencies/genomeCoverageBed"
        state=link

- name: intersectBed
  file: src="{{ GALAXY_HOME }}/tool-dependencies/bedtools"
        dest="{{ GALAXY_HOME }}/tool-dependencies/intersectBed"
        state=link

- name: multiIntersectBed
  file: src="{{ GALAXY_HOME }}/tool-dependencies/bedtools"
        dest="{{ GALAXY_HOME }}/tool-dependencies/multiIntersectBed"
        state=link

- name: unionBedGraphs
  file: src="{{ GALAXY_HOME }}/tool-dependencies/bedtools"
        dest="{{ GALAXY_HOME }}/tool-dependencies/unionBedGraphs"
        state=link

- name: bwa_default
  file: src="{{ GALAXY_HOME }}/tool-dependencies/bwa/0.5.10"
        dest="{{ GALAXY_HOME }}/tool-dependencies/bwa/default"
        state=link

- name: SICER_default
  file: src="{{ GALAXY_HOME }}/tool-dependencies/SICER/1.1"
        dest="{{ GALAXY_HOME }}/tool-dependencies/SICER/default"
        state=link

- name: bowtie2_default
  file: src="{{ GALAXY_HOME }}/tool-dependencies/bowtie2/2.1.0"
        dest="{{ GALAXY_HOME }}/tool-dependencies/bowtie2/default"
        state=link

- name: cufflinks_default
  file: src="{{ GALAXY_HOME }}/tool-dependencies/cufflinks/2.1.1"
        dest="{{ GALAXY_HOME }}/tool-dependencies/cufflinks/default"
        state=link

- name: freebayes_default
  file: src="{{ GALAXY_HOME }}/tool-dependencies/freebayes/0.9.4"
        dest="{{ GALAXY_HOME }}/tool-dependencies/freebayes/default"
        state=link

- name: htseq_default
  file: src="{{ GALAXY_HOME }}/tool-dependencies/htseq/0.5.3p9"
        dest="{{ GALAXY_HOME }}/tool-dependencies/htseq/default"
        state=link

- name: macs_default
  file: src="{{ GALAXY_HOME }}/tool-dependencies/macs/1.3.7.1"
        dest="{{ GALAXY_HOME }}/tool-dependencies/macs/default"
        state=link

- name: macs14_default
  file: src="{{ GALAXY_HOME }}/tool-dependencies/macs14/1.4.2"
        dest="{{ GALAXY_HOME }}/tool-dependencies/macs14/default"
        state=link

- name: numpy_default
  file: src="{{ GALAXY_HOME }}/tool-dependencies/numpy/1.6.2"
        dest="{{ GALAXY_HOME }}/tool-dependencies/numpy/default"
        state=link

- name: sambamba_default
  file: src="{{ GALAXY_HOME }}/tool-dependencies/sambamba/0.3.3"
        dest="{{ GALAXY_HOME }}/tool-dependencies/sambamba/default"
        state=link

- name: samtools_default
  file: src="{{ GALAXY_HOME }}/tool-dependencies/samtools/0.1.18"
        dest="{{ GALAXY_HOME }}/tool-dependencies/samtools/default"
        state=link

- name: tophat_default
  file: src="{{ GALAXY_HOME }}/tool-dependencies/tophat/1.4.0"
        dest="{{ GALAXY_HOME }}/tool-dependencies/tophat/default"
        state=link

- name: tophat2_default
  file: src="{{ GALAXY_HOME }}/tool-dependencies/tophat2/2.0.8b"
        dest="{{ GALAXY_HOME }}/tool-dependencies/tophat2/default"
        state=link
